### ISSUE TITLE
Support for MSYS2 / MINGW

### ISSUE THREAD

**Issue by danyeaw** [indygreg/PyOxidizer#114]
In order to run some applications in Windows, like PyGObject GUI ones, MSYS2 with MINGW is needed in order to build the libraries with GCC for Windows. I understand that the python-build-standalone project is using MSVC for the Windows build. Would it be the right approach and how difficult would it be to add support for MSYS2/MINGW as well?

Pyoxidizer installed successfully using mingw-64 rust, but when I try to initialize a sample pyapp it gives: `error occurred: Failed to find tool. Is `cl.exe` installed?`

**Comment by lorenzogatti** [comment]
I think the best solution for this and many other limitation would be to allow packaging of existing extension dynamic link libraries (alongside the main executable) from a virtualenv or from the main Python installation instead of insisting on compiling everything on the spot. 

Apart from extensions without readily available sources, many Python extensions are even harder to build than PyGObject (e.g. there's an issue about Lxml downloading stuff from the network), and expecting PyOxidizer to handle everything isn't a good goal.
