### ISSUE TITLE
Support building a `python` workalike binary

### ISSUE THREAD

**Issue by gnprice** [indygreg/PyOxidizer#122]
This is a proposed feature, something I'd love to use PyOxidizer for:

I have a library. I'd like to write Python scripts that use that library... and then I'd like to be able to distribute the scripts, and have a nice short route to being able to run them. Sometimes this means distributing to various machines, other times to contributors to some project (unrelated to the library) -- i.e., to anyone who clones the project's repo and installs its dev dependencies. For bonus points, I want to write the scripts and/or the library against a nice modern Python... and who knows what Python version someone wanting to contribute to $project might have lying around, if any.

A solution I think would be lovely is to build a binary (call it `python-mylibrary`) which works just like the `python` executable you might have in `/usr/bin/`... except (a) `import mylibrary` works out of the box; (b) it's the latest Python release. Then I just need to distribute that self-contained binary, which is more or less a solved problem.

It seems like PyOxidizer would be an excellent tool for doing this. AFAICT it doesn't yet out of the box support it, though. The closest I see in the config is to set `embedded_python_run.mode` to `repl`... but that mode is 100% what it says on the tin, in that the binary ignores its arguments and always just starts a REPL.

I think a good way of invoking such a feature might look like a value of `embedded_python_run.mode` named, say, `interpreter` -- the resulting binary not only contains a Python interpreter on the inside, but exposes one on the outside, and in particular it serves as an interpreter in the sense required by a shebang line like `#!python-mylibrary`.

I know CPython offers some APIs to do something like this, both at the Python stdlib level and the C API level. So I think the implementation of this feature will (fortunately!) require something less than reimplementing in Rust all the particular behavior of a `/usr/bin/python`.

I'll take a look at what the Python stdlib offers in this direction. If that's good enough, then I might be able to get most of what I want with something like a snippet passed to `embedded_python_run.mode = eval`, and then an example mentioned in the docs would be a good solution. If not, then the C API it'll be.

**Comment by indygreg** [comment]
This is a legitimate feature request. I believe there is effectively a `main()` we can call from PyOxidizer to simulate the behavior of the `python` application.

**Comment by jayvdb** [comment]
If not, we could borrow a pure python one from PyPy or similar.
A basic one is needed for https://github.com/indygreg/PyOxidizer/issues/152

**Comment by indygreg** [comment]
Looking at this some more, implementing this requires a non-trivial amount of work :/

The Python C API offers a `Py_Main()` that can basically be used inside an `int main(...)` to do what `python` does. This is convenient. But I think it is prohibitively too high level for use by PyOxidizer. This function will call `Py_Initialize()`, `Py_Finalize()` and everything in between. PyOxidizer needs to delicately call Python interpreter initialization functions in such a way to prime the environment for use by PyOxidizer.

For PyOxidizer to provide a `python` implementation with minimal effort, we would need a CPython API for things like parsing command arguments but without the interpreter initialization and finalization bits. Knowing the CPython API, I'm guessing they would balk at the idea because various command arguments translate to interpreter configuration settings that need to be set *before* the interpreter is initialized. So providing an API that claims to provide these arguments but doesn't do anything meaningful with them doesn't make that much sense. Although maybe a CPython maintainer will feel otherwise...

I think the best we can do here is reimplement the subset of the `python` command arguments we can support and hopefully that will be "good enough."

There is an outside chance that we can coerce `Py_Main()` into working with PyOxidizer by relying on changes to global/static variables within the interpreter. But I'd have to spend a bit of time stepping through code to verify that. I think the path of least resistance is to implement our own argument parser that consumes the arguments we can support and go from there.

Also, Python 3.8 offers some new APIs around interpreter configuration and initialization that may make an implementation vastly simpler...

**Comment by indygreg** [comment]
Looking at the Python 3.8 APIs in more detail, I think they offer enough flexibility to implement a `python` like executable with minimal effort. However, these APIs are Python 3.8+ only. And it would be quite difficult to make PyOxidizer work with both sets of APIs. So this will likely happen after PyOxidizer goes Python 3.8+ only. I feel like Python 3.8 might be mature enough to make that leap soon...

**Comment by gnprice** [comment]
Cool, thanks for investigating this!

FWIW, for my use case -- basically to use in a shebang line on a script -- I'd be perfectly happy if only a tiny subset of the `python` CLI were supported.

In fact, I think it would work just fine if it supported no options at all -- just one positional argument as the script to be run, and further positional arguments to stick in `sys.argv[1:]`. Like this:
```
usage: python-mylibrary SCRIPTFILE [ARG]...
```

It'd probably be convenient for development/debugging if it also supported `-c CMD`; `-V` for the version; and maybe `-h`/`--help`. After that, I think it's rapidly diminishing returns.

So if reusing the argument parsing is a particularly sticky part, then skipping that sounds like a great strategy to me.

**Comment by indygreg** [comment]
PyOxidizer 0.9 has support for building an executable that behaves like `python`. And this is documented at https://pyoxidizer.readthedocs.io/en/v0.9.0/packaging_python_executable.html. There are still some rough edges. But I think it is enough to consider this issue closed!

Please file new issues to request incremental feature improvements.
