### ISSUE TITLE
comparison to py2exe / feature to load DLLs from memory to memory

### ISSUE THREAD

**Issue by HaraldArminMassa** [indygreg/PyOxidizer#17]
Hi, wonderfull project! I am using py2exe for nearly 2 decades, missing it for 3.x so I am totally looking forward to oxidize my code.

Anyhow, via zipfile=None py2exe offers to create a truly single file exe for a python 2.x application; which includes all .pyc AND also all .dll files.

The most fascinating feature is within this code:

https://sourceforge.net/p/py2exe/svn/HEAD/tree/trunk/py2exe/source/MyLoadLibrary.c

That allows to load the .dll file FROM the single file exe into memory. Most likely not a zero copy way, BUT: this allows to use c-extensions (.pyd and similiar) to be packed into the single file .exe

py2exe licence is liberal enough to use inspiration from this code:
https://sourceforge.net/p/py2exe/svn/HEAD/tree/trunk/py2exe/docs/LICENSE.txt

And, reading in the project status of pyoxidizer:
"""
C Extensions
Building and using compiled extension modules (e.g. C extensions) is not yet supported. This is a hard problem on a few dimensions. We have a plan to solve it, however."""

maybe those links may be useful,

Cheers.

Harald

**Comment by sim0nx** [comment]
What about https://www.pyinstaller.org . Has been around for a long time, is stable and works for Py3

**Comment by indygreg** [comment]
I am aware of `py2exe`'s support for loading shared libraries from memory! This is a feature that Windows has that `glibc` and other platforms lack! Search https://gregoryszorc.com/blog/2018/12/18/distributing-standalone-python-applications/ for `dlopen_with_offset`. And `py2exe` has some pretty low-level code for getting that to work with Python. It's a technically impressive solution!

I also want to say that I'm pretty sure any prior solution that embeds Python modules in an executable extracts them to a filesystem (either as standalone `.py`/`.pyc` files or as a zip file) before loading them. I'm quite confident of that because I believe the hack PyOxidizer employs to load the *entirety* of the Python standard library from memory is new and novel. That is documented at https://github.com/indygreg/PyOxidizer/blob/master/pyoxidizer/src/pyembed/lib.rs. (I may want to move those docs outside the crate so they can be more easily read...) I encourage other Python packaging tools to steal this idea.

It sounds like I need to update https://pyoxidizer.readthedocs.io/en/latest/comparisons.html with more details. I'll try to do that in ~10 hours.

Thanks for the feedback.

**Comment by HaraldArminMassa** [comment]
"I also want to say that I'm pretty sure any prior solution that embeds Python modules in an executable extracts them to a filesystem (either as standalone .py/.pyc files or as a zip file) before loading them."

the other option (and the hack used by py2exe) is "the exe is a zipfile" - i.e., the created standalone exe is reopened as a zipfile - and python can import from zipfiles for ages. Additionally, zipfiles may have some strange bytes in the beginning not affecting them being zipfiles. (learned that when I unzipped a py2exe created file).

So, looking forward to more hacks to have the .dlls somehow frozen in the exe... unzipping to drive gives slow startup and other small troubles (left over files on crash i.e....)

thanks for your work, cheers Harald
