### ISSUE TITLE
Documentation should describe using standalone importlib_resources for Python < 3.7

### ISSUE THREAD

**Issue by warsaw** [indygreg/PyOxidizer#177]
The [documentation](https://pyoxidizer.readthedocs.io/en/latest/packaging_pitfalls.html#no-file) seems to imply that using the `importlib.resources` API won't work for Python < 3.7.  While it's true that that module was introduced into the stdlib in 3.7, there *is* a standalone package that's designed to work with Python back to 2.7 (actually, 2.7, 3.4-3.6 with shims for 3.7 and 3.8).

The question is, does PyOxidizer's resource reader support work for standalone [importlib_resources](https://importlib-resources.readthedocs.io/en/latest/index.html)?  If not, I would certainly be open to fixes that help.

The documentation should point to the standalone `importlib_resources` PyPI package for Python's < 3.7.

**Comment by jayvdb** [comment]
As PyOxidizer doesnt have py36 builds, and I doubt there will be anyone investing in setting them up, perhaps the doc should be more clear that PyOxidizer is py37+ at the moment, and then not discuss extra complications for pre 3.7 through the rest of the docs.

**Comment by indygreg** [comment]
I looked at the source for `importlib_resources` briefly and it appears to use `importlib.resources` if executing on Python 3.7. So it should work with PyOxidizer (to the extent that PyOxidizer's resources API is implemented correctly - I believe there are a few known bugs).

Since projects in the wild may wish to use `importlib_resources` in order to support Python <3.7 outside of PyOxidizer, I think it is a terrific idea to call out support for `importlib_resources` in PyOxidizer's documentation. Thanks for the suggestion, Barry!

**Comment by indygreg** [comment]
At some point after this issue was filed, I overhauled the resource loading documentation. https://pyoxidizer.readthedocs.io/en/v0.9.0/oxidized_importer_resource_files.html is the latest version. And it does recommend use of `importlib_resources`. So I think we can call this issue closed.
