### ISSUE TITLE
Cannot build app

### ISSUE THREAD

**Issue by BiatuAutMiahn** [indygreg/PyOxidizer#219]
Build: geadda2d
```
...
PyOxidizer does not set __file__ and this may create problems at run-time
See https://github.com/indygreg/PyOxidizer/issues/69 for more
package README.txt does not exist; excluding resources: ["README.txt"]
package bin does not exist; excluding resources: ["chardetect.exe"]
deriving custom importlib modules to support in-memory importing
building with Rust 1.42.0-nightly
    Updating crates.io index
error: no matching package named `pyembed` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
...
```

**Comment by BiatuAutMiahn** [comment]
When using cargo `install pyoxidizer` it builds fine

**Comment by indygreg** [comment]
`error: no matching package named `pyembed` found` is likely due moving `pyembed` to its own distributable package in the next release.

How did you build/install `pyoxidizer` to receive this error? I'm assuming you checked out an unreleased commit from the `main` branch? I need to know the sequence of commands you performed so I can reproduce this failure and fix this bug.

**Comment by BiatuAutMiahn** [comment]
I tried using the cargo git option, and tried downloading the repo itself and running `cargo install --path pyoxidizer` there were times I saw pyembed pass the compilation log but still, when building same issue.

**Comment by BiatuAutMiahn** [comment]
Oh, as for which build, I pulled from main, as indicated in the `Getting Started`

**Comment by pharaujo** [comment]
I had the same problem when I tried installing from the `main` branch as documented in the `Getting Started` page. To overcome this issue, I had to build a patched version of pyoxidizer with this change:

```diff
diff --git a/pyoxidizer/src/project_layout.rs b/pyoxidizer/src/project_layout.rs
index 35e4b7f..fbc7ebf 100644
--- a/pyoxidizer/src/project_layout.rs
+++ b/pyoxidizer/src/project_layout.rs
@@ -242,7 +242,7 @@ pub fn update_new_cargo_toml(path: &Path, pyembed_location: &PyembedLocation) ->

     content.push_str(&match pyembed_location {
         PyembedLocation::Version(version) => format!(
-            "pyembed = {{ version = \"{}\", default-features=false }}\n",
+            "pyembed = {{ version = \"{}\", default-features=false, git = 'https://github.com/indygreg/PyOxidizer', branch = 'main' }}\n",
             version
         ),
         PyembedLocation::Path(path) => format!(
```

**Comment by indygreg** [comment]
The current state of the `main` branch is a bit funky since the `pyembed` crate was converted to be a published crate. But we haven't yet published that crate. So only running out of the `PyOxidizer` Git repository will work until we do so.

The change from the previous comment is a good workaround. But it won't be necessary after the next release.

Since you are running into this problem, I'm tempted to publish a major version release just to get this change out the door. Let me think about it. (There's some half-finished features in `main` I would prefer to finish or disable before cutting a release.)

**Comment by pharaujo** [comment]
Would it make sense to take `pyembed` out from the `pyoxidizer` repo into its own, so that you could cut releases in separate schedules? That way you could possibly publish `pyembed` without cutting a `pyoxidizer` release, and have the `main` branch working out-of-the-box. Or did you mean you have half-finished features in `pyembed`?

**Comment by indygreg** [comment]
I want to keep `pyembed` in the same repository so I can make changes to both projects in the same atomic commit. Things will likely remain in this state indefinitely.

In other news, I just released 0.6.0. So a `cargo install pyoxidizer` should _just work_ now (hopefully).

**Comment by pharaujo** [comment]
Just tested 0.6.0, it works out of the box. This issue can probably be closed.

**Comment by layday** [comment]
This is happening again when installing from git now that pyembed has been bumped to 0.7.0-pre.

**Comment by mardukbp** [comment]
The same happens with 0.8.0-pre. @indygreg Please consider temporarily using the workaround in the [comment above](https://github.com/indygreg/PyOxidizer/issues/219#issuecomment-585172464) so that we can continue to test PyOxidizer using the main branch.

**Comment by trevyn** [comment]
As a reminder, since it wasn't super-obvious to me, you can run `pyoxidizer` straight from the repo without installing, and without making the above patch. For example:

`PyOxidizer $ cargo run -p pyoxidizer -- run`

This will pull in `pyembed` from the repo instead of crates.io.
