### ISSUE TITLE
Implement inclusive module filter?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [indygreg/PyOxidizer#221]
it seems that `extension_module_filter` only has presets, but what if we would like to include only needed modules via a list?

**Comment by indygreg** [comment]
This is possible with https://pyoxidizer.readthedocs.io/en/stable/config_api.html#pythonexecutable-filter-from-files-files-glob-patterns. But we should make it easier to do this when converting the `PythonDistribution` to a `PythonExecutable` in Starlark.

**Comment by BiatuAutMiahn** [comment]
Ah, I interpreted that option as an exclusion filter, I will try it.

**Comment by BiatuAutMiahn** [comment]
```
error[CV00]: Cannot .filter_from_files on type PythonExecutable
   --> .\pyoxidizer.bzl:120:5
    |
120 |     exe.filter_from_files(files=["./includes.txt"])
    |     ^^^^^^^^^^^^^^^^^^^^^ .filter_from_files not supported for type PythonExecutable
```

**Comment by BiatuAutMiahn** [comment]
I apologize for the ambiguity, here is the scope of this issue:
I have a python program that utilizes the requests library. I have the pip deps setup properly and when `extension_module_filter='all'` everything works fine after patching requests to work without __files__. However, when `extension_module_filter='minimal'` the build succeeds, however fails to run with error:
```
Traceback (most recent call last):
  File "pyModCheck.pyModCheck", line 7, in <module>
  File "requests.requests", line 43, in <module>
  File "urllib3", line 7, in <module>
  File "urllib3.connectionpool", line 7, in <module>
  File "socket", line 49, in <module>
ModuleNotFoundError: No module named '_socket'
SystemError
```
As for this issue, i figured that I might be able to manually include _socket, but I am unsure how.

**Comment by BiatuAutMiahn** [comment]
```
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import _socket
>>> _socket.__file__
'C:\\Program Files\\Python37\\DLLs\\_socket.pyd'
>>>
```

**Comment by indygreg** [comment]
I believe the new Starlark functionality allowing you to define a function that influences resource handling (https://pyoxidizer.readthedocs.io/en/v0.9.0/packaging_resources.html#using-callbacks-to-influence-resource-attributes) is sufficient to satisfy the request in this issue so I'm closing this issue.

Since so much has changed in Starlark, if you would like additional functionality to make filtering resources easier, please file a new issue framed in the context of current Starlark features. This will make the request much easier to understand.
