### ISSUE TITLE
Provide a standalone exe for PyOxidizer

### ISSUE THREAD

**Issue by ksamuel** [indygreg/PyOxidizer#23]
Many of the present and future Github issues are and will be related to failed builds from bad versions of rust, cargo, or just difficulties of installing them. To save you a lot maintenance overhead, and to make it easier for the end user, you probably want to provide and exe, a deb and an appimage for PyOxidizer so that beginners don't have to learn the rust ecosystem at first.

E.G: 

At the end of installaling PyOxidizer, I get a "warning: be sure to add `/home/user/.cargo/bin` to your PATH to be able to run the installed binaries". After years of teaching, I know that plenty of my student will google your tool, try to turn their script into an exe, and fail because they don't know how to set an env var (and don't even know what it is). It's good for them to learn it, but a few of them will just open an issue here and consume your time. 

Another example is the fact that PyOxidizer works only with Rust 1.34+ according to #18, but Ubuntu 16.04, the currently most popular LTS, only ships with 1.32 in the repos. Again beginners will fail, and probably won't find the answer by googling, eventually opening yet another ticket here.

**Comment by indygreg** [comment]
I generally agree with you here: I'm a huge proponent of _it just works_ and I understand that *any* obstacles interfering with initial usage can significantly curtail adoption. Having to install [a modern] Rust is potentially a huge hurdle.

I would like to eventually supply pre-built executables for `pyoxidizer`. This is easily within the domain of possibility. That being said, I don't think it is critical at this time mostly because of the general youth of the project. It feels like there are far more important things to work on (such as features). Furthermore, even if we provide a pre-built executable, you still need a Rust toolchain installed to build executables. This feels out of scope for PyOxidizer. (To argue otherwise would be to say that tools like `pip` should install a C compiler. I want to agree and support _it just works_. But there is a limit to my support of turnkey UX.)

My opinion on pre-built executables could be swayed by the existence of reports that building `pyoxidizer` itself is not reliable. The set of dependencies required to build `pyoxidizer` is non-trivial and I could see more people being tripped up by that than by installing Rust. So if I see even a few more reports saying "building PyOxidizer is hard" I will probably prioritize pre-built executables.

I am very sympathetic to the argument that the too-new Rust 1.34+ is required. We could probably get that version requirement down to 1.32 (or 1.31 - the first "Rust 2018 edition" release). Would you mind filing a new issue to track just that request?

**Comment by ksamuel** [comment]
With pleasure: https://github.com/indygreg/PyOxidizer/issues/24

BTW, I love your project. I'm a very experienced Python dev, so if you need me to do testing for you, ping me.

**Comment by nathanielmanistaatgoogle** [comment]
As someone today trapped in a twisty maze of
* Installing PyOxidizer requires installing Rust
* After installing Rust, Installing PyOxidizer directly or transitively requires installing openssl-sys
* [Installing openssl-sys requires installing a new OpenSSL on my system](https://users.rust-lang.org/t/trying-out-webassembly-cargo-install-cargo-generate-is-causing-errors/31408)
* Installing a new OpenSSL on my system requires installing Homebrew

... I would like to contribute that there are ergonomic issues in getting started with PyOxidizer and that I believe a standalone single-file PyOxidizer would be very welcome.

In the spirit of "[[your target user] shouldn't need to know anything about Python packaging, Python itself, or even the existence of Python in order to use your application](https://gregoryszorc.com/blog/2019/06/24/building-standalone-python-applications-with-pyoxidizer)" I would like to contribute that it would be a smooth and productive experience to simply [`./my_virtual_environment/bin/pip install --upgrade pyoxidizer`](https://github.com/indygreg/PyOxidizer/issues/101) and then `./my_virtual_environment/bin/python -m pyoxidizer` to turn a tree of Python code and data resources into a single executable file without any awareness that the tool for doing so was implemented in Rust. I wouldn't mind the size issues of there being an entire Rust toolchain under the hood.

@indygreg: would you like a separate issue filed for `pip install pyoxidizer` or would that developer journey be in the scope of this issue?

**Comment by indygreg** [comment]
As of a few releases ago, we are now publishing PyOxidizer wheels, executables, and Windows installers as part of the release artifacts. See e.g. https://github.com/indygreg/PyOxidizer/releases/tag/pyoxidizer%2F0.17. Newer versions of PyOxidizer also manage the Rust toolchain for you, so end-users don't have to worry about installing Rust to build binaries.

This is quite an old issue and I'm going to call it closed. If I missed anything or you want to request a new feature, please file a new issue.
