### ISSUE TITLE
run_module not running module

### ISSUE THREAD

**Issue by n8henrie** [indygreg/PyOxidizer#233]
Hello,

I'm trying to adapt [my fishing report script][0] to use pyoxidizer 0.6.0 (previously working on 0.4-ish).

The script uses [`__main__.py`][1] in the package to manage the CLI portion, and runs fine using e.g. `python -m nmfishingreport --help`.

Interestingly, using pyoxidizer 0.6.0 and `run_module="nmfishingreport"`, I get no output and a 0 exit code.

It looks like I have to use `run_module="nmfishingreport.__main__"` to get it to work as expected.

Is this normal behavior? I had expected `python -m blah` and `run_module="blah"` to behave the same.

[0]: https://github.com/n8henrie/nmfishingreport
[1]: https://github.com/n8henrie/nmfishingreport/blob/master/src/nmfishingreport/__main__.py

**Comment by indygreg** [comment]
This is a borderline bug, since `python -m <module>` appears to use `<module>.__main__` behind the scenes. That behavior is somewhat surprising to me, but I understand it.

Your workaround of specifying `run_module="<module>.__main__"` should work and makes this a low-priority. I'll add it to the backlog to look into emulating Python's behavior. At the very least, we should document the discrepancy.

Thank you for reporting this issue.

**Comment by indygreg** [comment]
PyOxidizer 0.8 and newer should now be using the mechanisms in the CPython APIs for running modules and behavior with PyOxidizer should hopefully be essentially identical to what `python -m <module>` does. So I'm closing this.

Please reopen this issue or file a new one if you feel things are still buggy.
