### ISSUE TITLE
Request a lower version of Rust 

### ISSUE THREAD

**Issue by ksamuel** [indygreg/PyOxidizer#24]
Quote from https://github.com/indygreg/PyOxidizer/issues/23:

>I am very sympathetic to the argument that the too-new Rust 1.34+ is required. We could probably get that version requirement down to 1.32 (or 1.31 - the first "Rust 2018 edition" release)

**Comment by indygreg** [comment]
I _think_ generated Rust projects build with 1.32 today. And 1.31 (if not earlier versions) is probably easily attainable given the small surface area of Rust code in generated projects.

`pyoxidizer` itself may require different versions. But since we can distribute standalone executables for `pyoxidizer` to sidestep Rust version requirements, it feels like the minimum version in generated projects is the bigger issue.

What I'm trying to say is I think this is a reasonable request :)

**Comment by indygreg** [comment]
PyOxidizer itself and built applications now require Rust 1.31, the first Rust 2018 edition release. We could potentially go lower. But it is considerably more effort. I'd very much like to be on Rust 2018 edition because the Rust community creates those editions with the intent of being stable and popular targets (as far as I understand things). I'd like to support that effort.
