### ISSUE TITLE
pyembed version mismatch

### ISSUE THREAD

**Issue by fgadaleta** [indygreg/PyOxidizer#254]
I tried both `$ pyoxidizer init-config-file pyapp` and `$ pyoxidizer init-rust-project pyapp`
after cloning repo and `cargo install --path pyoxidizer` 

Below is what I get 

```
error: failed to select a version for the requirement `pyembed = "^0.8.0-pre"`
  candidate versions found which didn't match: 0.7.0, 0.6.0
  location searched: crates.io index
required by package `pyapp v0.1.0 (/home/frag/Documents/test-pyoxi/pyapp)`
```

**Comment by indygreg** [comment]
Hmmm. So the issue here is that the generated Rust project attempts to blindly use `pyembed 0.8.0-pre` but can't find it.

Ideally the autogenerated projects when built from a pre-release of PyOxidizer would behave better here.

Until we have a solution in place, the workaround would be to use `pyoxidizer init-rust-project` and then modify the `Cargo.toml` to point to the Git checkout of PyOxidizer and grab `pyembed` from there. https://github.com/indygreg/PyOxidizer/blob/48a4cab593a53a1c11bf313981f6b29818941ee0/pyembed/Cargo.toml#L22 gives an example of how to tell Rust to pull in a crate from a Git repo or a local path.

**Comment by indygreg** [comment]
I think this is fixed in the `main` branch. Could you please install the latest code via `cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main pyoxidizer` and paste the output of `pyoxidizer --version` to confirm?

**Comment by indygreg** [comment]
People in other similar issues have reported that this is fixed in the `main` branch. So I'm going to close this issue.
