### ISSUE TITLE
cargo build fails 

### ISSUE THREAD

**Issue by fgadaleta** [indygreg/PyOxidizer#255]
`cargo build` fails with many errors, almost all related to `pyffi`

```error[E0433]: failed to resolve: could not find `PyPreConfig` in `pyffi````

**Comment by indygreg** [comment]
`cargo build` of what?

If you are attempting a `cargo build` of the entire workspace, this failure is likely coming from the `pyembed` crate. With default features, it will find a `python3` in `PATH` and use whatever it finds. We don't have good validation in place that it actually found a correct version. Since it is complaining about a symbol introduced in Python 3.8, you can workaround this by setting `PYTHON_SYS_EXECUTABLE=/path/to/python3.8` to force the `python3-sys` crate to use an explicit Python executable instead of whatever it finds in `PATH`.

Building the `pyembed` crate is kinda finicky because of the Python dependencies. When building PyOxidizer, it is best to stick with `cargo build -p pyoxidizer`.
