### ISSUE TITLE
How to select Python [3.8] version?

### ISSUE THREAD

**Issue by askoretskiy** [indygreg/PyOxidizer#256]
I have an app that requires Python3.8 version.

I was following the instruction:

```
pyoxidizer init-config-file myapp
cd myapp
pyoxidizer run
```

That resulted in pyoxidizer to download Python3.7:
```
resolving 1 targets
resolving target exe
resolving target dist
resolving Python distribution Url { url: "https://github.com/indygreg/python-build-standalone/releases/download/20200408/cpython-3.7.7-macos-20200409T0412.tar.zst", sha256: "f312bea46a7d8efecd4df6b22c03f83016775e6bb5944a5701d697e0a52c63b2" }
downloading https://github.com/indygreg/python-build-standalone/releases/download/20200408/cpython-3.7.7-macos-20200409T0412.tar.zst
Python distribution available at /Users/tonnzor/my_projects/group_select_with_customer/pydatahub/datahub/./build/python_distributions/cpython-3.7.7-macos-20200409T0412.tar.zst
```

I've checked documentation and `pyoxidizer.bzl` file and could not find any place to specify exact Python version. At the same time it seems Python 3.8 is supported.

It would be nice it anyone could give any idea about that. Also, one might extend documentation to include this.

**Comment by askoretskiy** [comment]
OK, it seems there is a section for it https://pyoxidizer.readthedocs.io/en/stable/config_api.html#pythondistribution-sha256-local-path-none-url-none-flavor-standalone

The question is how to use this?

```
linux = PythonDistribution(
    sha256="11a53f5755773f91111a04f6070a6bc00518a0e8e64d90f58584abf02ca79081",
    local_path="/var/python-distributions/cpython-linux64.tar.zst"
)
macos = PythonDistribution(
     sha256="b46a861c05cb74b5b668d2ce44dcb65a449b9fef98ba5d9ec6ff6937829d5eec",
     url="https://github.com/indygreg/python-build-standalone/releases/download/20190505/cpython-3.7.3-macos-20190506T0054.tar.zst"
)
```

Should I rewrite `make_dist`? Should I provide all the `PythonDistribution` for each OS?

**Comment by indygreg** [comment]
In theory you would be able to use the Python 3.8 distributions published at https://github.com/indygreg/python-build-standalone/releases. However, the initial Python 3.8 distributions used a newer version of the distribution format and aren't compatible with PyOxidizer 0.7.

The good news is that the current `main` branch supports Python 3.8. (We actually dropped support for Python 3.7 because we needed to leverage new C APIs introduced in Python 3.8.) This will eventually become PyOxidizer 0.8. I'm not yet sure when a release will occur. There are a few things that need shored up first. In the mean time, you should be able to `git clone` and `cargo install --path pyoxidizer` to install from source and get Python 3.8 support.

If that works for you, I don't think this issue is actionable and can be closed. Does the current `main` branch work for you?

**Comment by askoretskiy** [comment]
Thank you @indygreg for clarification. I'm trying it out now.

It seems the easiest way to install PyOxidizer from `main` branch is mentioned in the official documentation https://pyoxidizer.readthedocs.io/en/latest/getting_started.html#installing-pyoxidizer , i.e.:

```bash
cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main pyoxidizer
```

It works and it installs Python3.8. Though compiling project does not work:

```
pyoxidizer run
...
libpythonXY created
building with Rust 1.43.1
    Updating crates.io index
error: failed to select a version for the requirement `pyembed = "^0.8.0-pre"`
  candidate versions found which didn't match: 0.7.0, 0.6.0
  location searched: crates.io index
required by package `datahub v0.1.0 (/private/var/folders/xr/npmjbpqn1wz4vlnv3hrfswvh0000gn/T/pyoxidizer.hS04i9vODDzh/datahub)`
error: cargo build failed
```

When I've tried an approach with `git clone` and `cargo install --path` unfortunately gives the same result:

```
libpythonXY created
building with Rust 1.43.1
    Updating crates.io index
error: failed to select a version for the requirement `pyembed = "^0.8.0-pre"`
  candidate versions found which didn't match: 0.7.0, 0.6.0
  location searched: crates.io index
required by package `datahub v0.1.0 (/private/var/folders/xr/npmjbpqn1wz4vlnv3hrfswvh0000gn/T/pyoxidizer.ie4bjkfrKrPO/datahub)`
error: cargo build failed
```

Do you have any further hints?..

Back to initial request -- is it possible to add something like "Only Python3.8 is supported" or maybe even an compatibility table? That would remove a lot of confusion here.

**Comment by indygreg** [comment]
The latest error you encountered regarding the version string mismatch should hopefully be fixed on the `main` branch. You can install that latest version via `cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main pyoxidizer`.

I also have a commit queued that will add more docs around the Python 3.8 requirement. And the pending release of Python 3.9 will necessitate me to add Starlark primitives to define the requested version of the Python distribution.

I'm going to close this because I don't see any required further action. If you feel differently or are still encountering issues reported here, please reopen!
