### ISSUE TITLE
Failed to load source for a dependency on 'cpython'

### ISSUE THREAD

**Issue by platypushunter** [indygreg/PyOxidizer#30]
Please forgive me if this is just me being a noob, but im following the instructions in the getting started file, but when i do `pyoxidizer build` it runs for a bit, then raises the error 
error: failed to load source for a dependency on `cpython`

Caused by:
  Unable to update https://github.com/indygreg/PyOxidizer.git?tag=vUNKNOWN

Caused by:
  failed to find tag `vUNKNOWN`

Caused by:
  reference 'refs/tags/vUNKNOWN' not found; class=Reference (4); code=NotFound (-3)
error: cargo build failed

This is my first experience with rust or cargo so my apologies if this is something easy to fix, but google wasn't much help

**Comment by platypushunter** [comment]
same error when i do `pyoxidizer run`

**Comment by indygreg** [comment]
Which version of `pyoxidizer` are you using? (Run `pyoxidizer` and the version should be in the first line or 2).

I _thought_ the `UNKNOWN` issue was fixed in version `0.1.1`. But you may have found a different variation of the issue.

If you are running `0.1.2`, may I ask how you installed PyOxidizer? What operating system is this? Does `git` work from your terminal?

**Comment by platypushunter** [comment]
So from reading through some messages and other errors and stuff, i believe the version im supposed to be using is 0.1.2, however when i run pyoxidizer it says `PyOxidizer UKNOWN` im running the latest version of windows 10 home, and no git does not work, though i have had it in the past, im not sure why its not working right now(its possible i accidentally uninstalled it, i had to wipe a lot of my hard drive some time ago). i installed pyoxidizer with `cargo install pyxodizer`  then after this issue persisted i reinstalled it with `cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main pyoxidizer --force`

**Comment by sproutecks2125** [comment]
.Sent via the Samsung Galaxy S9, an AT&T 5G Evolution?a capable smartphone
-------- Original message --------From: platypushunter <notifications@github.com> Date: 6/27/19  9:51 AM  (GMT-06:00) To: indygreg/PyOxidizer <PyOxidizer@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [indygreg/PyOxidizer] Failed to load source for a dependency on 'cpython' (#30) So from reading through some messages and other errors and stuff, i believe the version im supposed to be using is 0.1.2, however when i run pyoxidizer it says PyOxidizer UKNOWN im running the latest version of windows 10 home, and no git does not work, though i have had it in the past, im not sure why its not working right now(its possible i accidentally uninstalled it, i had to wipe a lot of my hard drive some time ago). i installed pyoxidizer with cargo install pyxodizer  then after this issue persisted i reinstalled it with cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main pyoxidizer --force

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/indygreg/PyOxidizer/issues/30?email_source=notifications\u0026email_token=AHPM7ROD77YTJIOHF7V7QILP4THXTA5CNFSM4H3WCZ42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYXLZ7I#issuecomment-506379517",
"url": "https://github.com/indygreg/PyOxidizer/issues/30?email_source=notifications\u0026email_token=AHPM7ROD77YTJIOHF7V7QILP4THXTA5CNFSM4H3WCZ42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYXLZ7I#issuecomment-506379517",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by indygreg** [comment]
I may have introduced this bug when trying to fix another related issue.

As a workaround, try installing/running PyOxidizer from a _Git for Windows_ terminal prompt.

**Comment by platypushunter** [comment]
ok i shall

**Comment by platypushunter** [comment]
ok after installing the latest release of git and pyoxidizer master it works just like its supposed to. hope i contributed to something usefull, thanks for the help!

**Comment by indygreg** [comment]
I think the 0.8 release of PyOxidizer fixed issues with PyOxidizer failing to identify versions or references to dependency crates properly. So closing this issue.
