### ISSUE TITLE
Starlark load statement doesn't work

### ISSUE THREAD

**Issue by wkschwartz** [indygreg/PyOxidizer#328]
# Description

I would like to split my `pyoxidizer.bzl` into utility modules that I can distribute to coworkers (or just to make a large configuration file easier to navigate). Starlark's [`load`] statement supports this functionality, the Rust starlark crate [supports](https://docs.rs/starlark/0.3.1/starlark/eval/simple/index.html) `load` via [`starlark::eval::simple::eval_file`], and this is precisely the function PyOxidizer uses:
https://github.com/indygreg/PyOxidizer/blob/93af6273d6902aa04a05de3b6a1e5fd15d42f3b1/pyoxidizer/src/starlark/eval.rs#L63-L75

[`starlark::eval::simple::eval_file`]: https://docs.rs/starlark/0.3.1/starlark/eval/simple/fn.eval_file.html
[`load`]: https://github.com/bazelbuild/starlark/blob/master/spec.md#load-statements

# Test Case

Copy the first code block into `pyoxidizer.bzl` and the second into `helper.bzl` in an otherwise empty directory. Run `pyoxidizer build` with any recent version of PyOxidizer (I ran it from f654877 in #327, which doesn't touch Starlark itself).

```bzl
# pyoxidizer.bzl
load("helper.bzl", "make")
register_target("install", make, default=True)
resolve_targets()
```

----

```bzl
# helper.bzl
def make():
    dist = default_python_distribution()
    exe = dist.to_python_executable(
        name="pyapp",
        packaging_policy=dist.make_python_packaging_policy(),
    )
    files = FileManifest()
    files.add_python_resource(".", exe)
    return files
```
----
I would expect this to work as normal. Instead, I get the following output from `pyoxidizer build`:
```
error[CE03]: Cannot borrow environment mutably: Frozen
 --> ./pyoxidizer.bzl:1:20
  |
1 | load("helper.bzl", "make")
  |                    ^^^^^^ Frozen


error: Cannot borrow environment mutably: Frozen
```

# Analysis

This error is surprising because a Starlark [module](https://github.com/bazelbuild/starlark/blob/master/spec.md#module-execution) should not become [frozen](https://github.com/bazelbuild/starlark/blob/master/spec.md#freezing-a-value) until after the module has been evaluated:

> Immediately after execution of a Starlark module, all values in its top-level environment are frozen....
>
> Each Starlark file defines a module, which is a mapping from the names of global variables to their values. When a Starlark file is executed, whether directly by the application or indirectly through a `load` statement...
>
> If execution reaches the end of the file, module initialization is successful. At that point, the value of each of the module's global variables is frozen, rendering subsequent mutation impossible.

**Comment by wkschwartz** [comment]
@indygreg I see you've started working on this (9573fee). That's great. Let me know if there's something I can do to help---this is a moderately high priority item for me if the fix won't take too long. I'm a bit of a Rust newbie and I don't know my way around PyOxidizer's internals very well, but if there's any low hanging fruit, I can take a crack at it.

**Comment by indygreg** [comment]
I believe I fixed this in 2dbe0d259811a5f9cb43d142e2b9c1e989d0416d.

The refactoring to get this working was not low-hanging fruit and exposed some nuanced behavior of the Starlark crate that I wasn't aware of. But I'm reasonably confident that the refactored code does things more properly than before and we shouldn't run into similar issues due to misuse of the Starlark crate.

**Comment by wkschwartz** [comment]
Awesome. Thanks!

I'm testing it out now. In the loaded file, I can use global functions (e.g., `default_python_distribution`, `register_target`), but not global constants (e.g., `BUILD_TARGET_TRIPLE`). `True` and `False` do work though. I'm not sure why some symbols would get copied from the parent to the child environment but not others. The Starlark crate's documentation is... sparse. If that description is unclear to you, let me know and I'll come up with a test case.

Anyway, the global symbol issue isn't a blocker for me. I already need the loading file to pass a `dict` to the loaded file. I'll just add the few global constants to that dictionary and ensure access to it in all the functions the loaded file defines.

**Comment by indygreg** [comment]
The `Environment` (which is the thing containing variables) is different for the file calling `load()` and the file be loaded. These can't be the same exact object: the best we can do here is clone the current environment: that should make the variables from the calling file available to the file being loaded.

However, any variable mutations within the `load()`ed file will not be reflected outside that file's `Environment`.

Furthermore, if we attempt to clone and pass the child environment containing the variables to the loaded file's context, we get an error due to mutably borrowing a frozen variable. I'm unsure what is up here. It is possible we might be able to work around it.

Anyway, would you mind filing a new issue to document the new failure mode and desired outcome? It's possible that due to the way that we abuse global variables in Starlark, we may not be able to do what you want to do with multiple files. I just wanted to warn you.
