### ISSUE TITLE
WxPython module not found error

### ISSUE THREAD

**Issue by sander76** [indygreg/PyOxidizer#33]
I've got a very simple wx app:

```
import wx

def start_app():
    app = wx.App()

    frame = wx.Frame(None, title="Simple application")
    frame.Show()

    app.MainLoop()
```

It builds fine on my win10 machine, but when running the binary I get 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "ox_tester.wx_app", line 1, in <module>
  File "wx", line 17, in <module>
  File "wx.core", line 12, in <module>
ModuleNotFoundError: No module named 'wx._core'
```

maybe related to?:
https://github.com/indygreg/PyOxidizer/issues/25

**Comment by indygreg** [comment]
`ModuleNotFoundError` is usually different from `ImportError`: the former implies that the module isn't found and the later that it doesn't exist. I'm wondering if `wx._core` isn't packaged at all.

Is `wx._core` a C extension by any chance? Do you see any references to `wx._core` in the output of the build?

**Comment by sander76** [comment]
The build log mentions `_core.cp37-win_amd64.pyd` , which is part of the `wx` package.
I think this is the `wx._core` that the app is unable to find. I don't know how to recognize a C extension..

**Comment by sander76** [comment]
Updated to oxidizer ver 2. Now I don't see this error anymore. But now my installation halts at installing numpy (which is a dependency for wxpython)

There are some open issues on numpy. Keeping an eye on them..

**Comment by n8henrie** [comment]
I'm seeing this (missing `wx._core`) on pyoxizider 0.4.0 and wxpython 4.0.7.

**Comment by n8henrie** [comment]
Looks like the wxpython setup.py depends on a custom build command: https://github.com/wxWidgets/Phoenix/blob/master/setup.py which [can be a problem for pyoxidizer](https://pyoxidizer.readthedocs.io/en/latest/packaging_pitfalls.html#c-and-other-native-extension-modules).

I can see the shared library in question in my virtualenv: `.venv/lib/python3.7/site-packages/wx/_core.cpython-37m-darwin.so` -- is there any way to manually have pyoxidizer include or otherwise link with it?

Or can I manually have pyoxidizer run it? Looks like the setup.py just calls `cmd = ['"{}"'.format(sys.executable), '-u', 'build.py', 'build']`

**Comment by n8henrie** [comment]
@sander76 Are you now using wxpython with pyoxidizer smoothly?

**Comment by sander76** [comment]
> @sander76 Are you now using wxpython with pyoxidizer smoothly?

Not yet. But the wxpython works now. I have more challenges that I need to solve
