### ISSUE TITLE
Feature request, flag to disable cargo.lock and allow update

### ISSUE THREAD

**Issue by ryancinsight** [indygreg/PyOxidizer#396]
The addition of lock was a good Idea but would like the option to disable cargo.lock and update dependencies.

**Comment by indygreg** [comment]
I'm curious why you closed #395. Did the build not *just work* with the presence of `Cargo.lock`? The whole point of adding the `Cargo.lock` to autogenerated projects was to ensure determinism so local Cargo registry state wouldn't interfere with builds.

As for this issue, I have mixed feelings. The target audience of PyOxidizer is primarily Python developers. For them, Rust is an implementation detail and I don't want to burden them about Rust's existence too much. The *Rust developer mode* is the `pyoxidizer init-rust-project` workflow. (Although that isn't well-documented and is currently broken, it appears.)

I suppose we could add a CLI flag to disable the creation of the `Cargo.lock` file when materializing new Rust projects. But I'd prefer to point Rust developers at the workflow where they have a persisted Rust project instead of a temporary one.

**Comment by ryancinsight** [comment]
I closed #395 because it was my fault, I was trying to test changes to the memory allocators by setting paths to local forks and compiling but the lock was preventing me from making changes because I have not used it before.

For one, I think we should remove libc, I just did this for snmalloc and will probably try for mimalloc as well. libc  crate disgruntles me because I realized it is a glorified wrapper for normal rust calls like usize for size_t and u16 for wchar_t and thus adds 7 seconds to compilation and causes overhead that is unneeded.

**Comment by ryancinsight** [comment]
Disabling actually wouldn't change anything in pull requests though. Is there a process to update the pyembed lock template instead of manual changes?

**Comment by indygreg** [comment]
`cargo run --bin release -- generate-new-project-cargo-lock > pyoxidizer/src/new-project-cargo.lock`

**Comment by ryancinsight** [comment]
Thanks!
