### ISSUE TITLE
PyOxidizer cannot find `_posixsubprocess` on Linux

### ISSUE THREAD

**Issue by layday** [indygreg/PyOxidizer#406]
With PyOxidizer v0.16.2 from PyPI for Python 3.9, running `pip install` with the PyOxidizer provided copy of Python during build raises:

```
ModuleNotFoundError: No module named '_posixsubprocess'
```

See the repro at https://github.com/layday/pyoxidizer-linux-subprocess (https://github.com/layday/pyoxidizer-linux-subprocess/runs/2665887808?check_suite_focus=true).

**Comment by indygreg** [comment]
This is an extremely peculiar error because `_posixsubprocess` is compiled as a built-in extension module in the Linux distributions. I can confirm this via the following:

```
 ~/.cache/pyoxidizer/python_distributions/python.e4f28943fab7/python/install/bin/python3.9
Python 3.9.5 (default, May  6 2021, 20:17:24)
[Clang 12.0.0 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _posixsubprocess
>>> _posixsubprocess.__loader__
<class '_frozen_importlib.BuiltinImporter'>
```

Same results for the distribution with SHA-256 prefix `be3f8b6e72ba`, which is what your GitHub Actions build uses.

I'm unsure what's going on here. My guess is something environment variable related where different Python standard library paths are getting picked up or something. But that shouldn't matter, as built-in extension modules should always be loaded without issue, since `sys.meta_path[0]` should be `<class '_frozen_importlib.BuiltinImporter'>`. This will require more investigation.

**Comment by layday** [comment]
The issue only occurs when using [`actions/setup-python`](https://github.com/actions/setup-python).  Downloading the PyOxidizer binary and running it, without the GH Python, works.  On Linux, `actions/setup-python` injects these two variables in the environment:

```
pythonLocation: /opt/hostedtoolcache/Python/3.9.5/x64
LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.5/x64/lib
```

Dropping `$LD_LIBRARY_PATH` got PyOxidizer working again.

**Comment by indygreg** [comment]
Thanks for the context about `LD_LIBRARY_PATH`.

The standalone `python` has a shared library dependency on libpython. The loader directive built into the binary references a relative path to the standalone Python's directory containing its libpython. But if `LD_LIBRARY_PATH` is defined, it takes precedence over paths baked into the binary.

In the standalone Python builds, most extension modules are compiled as builtins: more extension modules than what typical Python builds do.

I think what's happening here is that the disagreement between which extension modules are builtins versus file based is causing the wrong module loader to be used at run-time, leading to a `ModuleNotFoundError`.

The most robust workaround for this is to change how the binaries are built so `LD_LIBRARY_PATH` doesn't factor into the libpython load. This can be done by changing the library name to have slashes or by using `DT_RPATH`. The former is preferred as the latter is deprecated.
