### ISSUE TITLE
Documentation error re Windows UCRT

### ISSUE THREAD

**Issue by j77h** [indygreg/PyOxidizer#419]
This message is out-of-date:
https://pyoxidizer.readthedocs.io/en/latest/pyoxidizer_distributing_windows.html
"The Visual C++ Redistributable is ***not*** a core Windows operating system component".
(I think I saw the same wrong message in the Python docs recently.)

This is why:
https://docs.microsoft.com/en-us/cpp/windows/universal-crt-deployment?view=msvc-160#local-deployment
"On Windows 10, the Universal CRT in the system directory is always used,
even if an application includes an application-local copy of the Universal CRT.
It's true even when the local copy is newer, because 
***the Universal CRT is a core operating system component on Windows 10***."

**Comment by indygreg** [comment]
The UCRT and the Visual C++ Redistributable are not the same thing! So I think the documentation is accurate.

You are correct that the UCRT is a core operating system component on Windows 10. However, the VC++ Redistributable files (e.g. `vcruntime140.dll`) are not. (But in reality the VC++ Redistributable DLLs are almost always installed at the system level because practically every application depends on them and will embed/run the VC++ Redistributable installer as part of its own installer.)

**Comment by j77h** [comment]
Thank you. My mistake. 
Since 2009 I've been privately distributing an app with a custom cut-down python interpreter. On Windows10, installing it has never needed a VCRT redist. When trying to find out if I could rely on that always being the case, I got the impression that UCRT was a new name for the one VCRT that covers all recent VC versions. Windows documentation is so verbose that I stopped reading too soon.
