### ISSUE TITLE
Is there support for creating static lib on mac osx?

### ISSUE THREAD

**Issue by katetsu** [indygreg/PyOxidizer#475]
Hi, 

I have an application which is supposed to run on linux and mac. no requirement for windows atm.
My application is written in rust and only one of its libs needs to include a python kernel as it needs to call python code.
Is there support for creating static libs with pyoxidizer?  - i have seen [this](https://pyoxidizer.readthedocs.io/en/stable/pyoxidizer_packaging_static_linking.html) but it says that only linux is supported.

Also, if not, is there a recommended way for this?

**Comment by indygreg** [comment]
Define _static lib_.

On macOS, it is effectively impossible to create a fully statically linked binary since nearly everything depends on some system library or framework. However, it is possible to produce binaries that only have a run-time dependency on macOS system libraries/frameworks that should always be present and are portable to macOS versions that are many years old. This is the closest most will get to statically linked executables on macOS. And this is the only option supported by PyOxidizer.

macOS binaries built with PyOxidizer will contain an embedded Python distribution that only has dependencies on macOS libraries and frameworks that ship with macOS. However, you may need to set some environment variables at build time to ensure binaries are portable to macOS versions older than the build machine. See https://pyoxidizer.readthedocs.io/en/stable/pyoxidizer_distributing_macos.html.

Does this answer your question?

**Comment by katetsu** [comment]
Thanks for the prompt response.

It is totally fine with having some deps on dynamic libs. im currently looking for a solution to integrate this within cargo. at the moment i use pyo3 to call python code from rust and pyo3 relies on having LD_LIBRARY_PATH defined in order to find the appropriate python lib. ideally i would like to use pyoxidizer to produce a static lib which would  resolve these paths. is there a guide for this?

also, if i were to include this as a static lib, is this going to have a stripped down version of the python lib? i.e. static libs drop unused symbols.

**Comment by indygreg** [comment]
I think https://pyoxidizer.readthedocs.io/en/stable/pyoxidizer_rust_generic_embedding.html will answer some of your questions.

**Comment by katetsu** [comment]
Thanks a lot @indygreg this resolved my question.

**Comment by katetsu** [comment]
One more question, is there a way to integrate pyoxidizer's commands in a cargo file? i know i can do this in build.rs but im asking whether there is already a tool for doing this:

in short, im interested in  building every by doing cargo build. 
so i would like to automate below commands:
```
 pyoxidizer generate-python-embedding-artifacts pyembedded
 PYO3_CONFIG_FILE=$(pwd)/pyembedded/pyo3-build-config-file.txt cargo test -p resource-manager
```
