### ISSUE TITLE
Include PYO3_CONFIG_FILE setting as part of build

### ISSUE THREAD

**Issue by katetsu** [indygreg/PyOxidizer#476]
Any way to specify `PYO3_CONFIG_FILE` within build.rs? 

I am generating the embedding artifacts under OUT_DIR and that changes every time and would like to automate the setting for `PYO3_CONFIG_FILE`.

Any ideas?

my currrent build script:

```rust
// build.rs

use std::process::Command;
use std::env;
use std::path::Path;
use std::fs;

fn main() {
    let out_dir = env::var_os("OUT_DIR").unwrap();
    let artifacts_path : String = Path::new(&out_dir).join("pyartifacts_em").to_str().unwrap().into();


    let dest_path = Path::new(&out_dir).join("pyoxidizer_gen.rs");
    fs::write(
        &dest_path, format!(
        r#"include!("{}/default_python_config.rs");
        "#, artifacts_path)
    ).unwrap();

    Command::new("pyoxidizer").args(&["generate-python-embedding-artifacts", &artifacts_path])
                       .status().unwrap();


    let key = "PYO3_CONFIG_FILE";
    let value = format!("{}{}",artifacts_path,"/pyo3-build-config-file.txt");

    println!("cargo:rustc-env={}={}", key, value);
}

```
this line doesnt seem to help replace ` println!("cargo:rustc-env={}={}", key, value);` 
`PYO3_CONFIG_FILE=path cargo build` with `cargo build`.

**Comment by indygreg** [comment]
Due to restrictions in the way Cargo works, the only way to control the build of a crate dependency is via feature selection. And features are defined as static strings and unknown features are rejected, so you can't pass dynamic metadata through feature strings, sadly.

Since `pyembed` depends on `pyo3*` crates, `pyembed` cannot pass dynamic metadata to `pyo3`'s build context. Instead, you have to do things like pass environment variables to the original `cargo` process which are then picked up by the dependency crates. This means that friendlier workflows (such as `pyembed` dynamically deriving an appropriate PyO3 config file and having `pyo3` use it) are not supported.

This is a large reason why `pyoxidizer build` needs to exist as a glorified wrapper around `cargo build`.

**Comment by katetsu** [comment]
Thanks for clarifying.

**Comment by Zenton** [comment]
For what it's worth, if someone in the future comes searching for this problem, there is a nice solution (at least, to my version of the problem) using [configurable-env](https://doc.rust-lang.org/nightly/cargo/reference/config.html#env) in Cargo.

In short, using `configurable-env` you can set environment variables via a `.cargo/config.toml` file (not as dynamic as your own build script, but straightforward for me use-cases).

For example, for me the solution was to create `$my_project/.cargo/config.toml` with:

```toml
[env]
PYO3_CONFIG_FILE = { value = "build-resources/pyembedded/pyo3-build-config-file.txt", relative = true }
```

`relative = true` converts the path to an absolute path (i.e. we end up with `$my_project/build-resources/pyembedded/pyo3-build-config-file.txt`).

Gregory -- thanks for the fantastic library!
