### ISSUE TITLE
multiphase initialisation suport of pyoxidizer

### ISSUE THREAD

**Issue by franzhaas** [indygreg/PyOxidizer#490]
Hi,

This is a reduced example to the issue https://github.com/indygreg/PyOxidizer/issues/489

Thanks to @rgommers to point me to the right direction

I made a minimal example showing how cython modules can break pyoxidizer single file executables on windows.

https://github.com/franzhaas/pyoxidizer_cython_example

when importing fib, the repl crashes.

versions used are documented in pipenv.lock.

I am new to pyoxidizer, and would apreciate if I could get some guidnace how to tackle this. Is this a regression? Has that been working with older versions? 

I do have access to working pyd files, which have been build out of hand crafted c code and will have a look at the difference between this and the cython c code, but this is likely not to work out....

Thanks for the grate tool!

**Comment by franzhaas** [comment]
I did look into that issue further.

I was able to create a pyd file that triggers this issue, without calling cython. The issue manifests itself after __Pyx_copy_spec_to_module passes its last log message.

The pyd files i got working without issues use sinlge phase initialisation, but the cython generated c code uses 2 phase initialisation. 

Did anyone have success with 2 phase initialisation?

**Comment by franzhaas** [comment]
I did try to install the extension as a sdist instead of a wheel, and achieved exactly the same result.

**Comment by franzhaas** [comment]
I did disable the 489 support when building the generated cython code. This created a working minimal example.

The code is in the minimal example.
https://github.com/franzhaas/pyoxidizer_cython_example


This example loads and works (in a view toy function calls). Therefore i think this  issue si truely due to the PEP489 multi phase loading.

I am willing to continue to work on that, but i a m unsure if the best angle of attack would be to add the feature to disable PEP 489 to cython, or to add 489 support to pyoxidizer. I am worried that to fix this inside of pyoxidizer i need a lot of internal knwoledge of the pyhton interpreter, python extentions and pyoxidizer, that i am lacking. On the other hand, adding a compile time option to cython apears to be trivial.

The goal i am actually trying to achieve is to have llvmlite numba and numpy in a sinlge file executeable.

**Comment by franzhaas** [comment]
I tried to follow this description.:
https://pyoxidizer.readthedocs.io/en/stable/oxidized_importer_freezing_applications.html#oxidized-importer-freezing

to try out if i can reproduce the issue with a standard python installation, and just the oxidized-importer, and i still observed a problem with multiphase initialisation.

**Comment by franzhaas** [comment]
This apears to be a use after delete error.

By calling Py_INCREF on the PyObject * received from calling PyModuleDef_Init, the crash can be avoided.

Thats odd...

**Comment by franzhaas** [comment]
https://github.com/indygreg/PyOxidizer/pull/494

This solves the issue for me.

**Comment by indygreg** [comment]
Thank you for filing this issue and for the thorough analysis!

There is indeed a subtle bug related to refcount handling and multi-phase initialization. While your PR purports to solve it, I'm not yet convinced that the refcount handling is sound. I'd like to spend some more time understanding what is going on before a solution is committed.

Given the complexity of this issue, there's a good chance I end up creating my own commits to fix this. That will likely be faster than iterating back and forth on a PR.

**Comment by indygreg** [comment]
Ahh - I think I know what the problem is!

In single phase initialization, the module init function calls `PyModule_Create()` or `PyModule_Create2()`, which returns a **new reference**.

In multi-phase initialization, the module init function calls `PyModuleDef_Init()`, which returns a **borrowed reference**.

Our current code is effectively reduced to:

```
let py_module = init_fn();
...
let py_module = unsafe { PyObject::from_owned_ptr(py, py_module) };
```

The `PyObject::from_owned_ptr()` call should only be used with an owned/new reference. But we're calling it with a borrowed reference in the case of multi-phase initialization.

What's happens in multi-phase initialization is that Rust is like "I own this object: there's no need to increment the reference count." But since that object is a borrowed pointer, something else is decrementing the refcount, causing it to go to 0 and the object to get finalized. But Rust still has a reference. Eventually we try to access the memory formerly occupied by this finalized object and a crash ensues. Classic use-after-free.

While your PR works, I think a better solution to this is to defer and conditionalize the `PyObject::from_owned_ptr()` call until we know if we're operating on an owned or borrowed reference. That way we don't have to muck with refcount APIs directly. Generally speaking, you shouldn't need to be concerned with refcounts in the Rust API because Rust's ownership model handles that for us. The existence of Python refcount APIs in Rust code is a smell that refcounting isn't... sound.

**Comment by franzhaas** [comment]
Nice, I understand, these where my very first lines of rust code, its to be expected that they are not great.

Using the chages discussed here, i run the testsuite of a modified numpy version.
https://github.com/franzhaas/numpy_sinlge_file_executable/actions

however it fails to run trough at the moment... dont know why yet...
