### ISSUE TITLE
Packaging_rule doesn't work as expected.

### ISSUE THREAD

**Issue by TxBillbr** [indygreg/PyOxidizer#51]
@indygreg - Great work! I am trying to get this operational on Windows10 and have a split project structure due to path lengths problem. So I have created the pyoxidizer project in c:\artipy and tried to point at my sources with a packaging rule.
```
[[packaging_rule]]
type = "package-root"
path = "C:/Users/BrotherB/PyCharmProjects/artipy"
packages = ["artipy"]
```
I have tried several alternative embedded_python_run options, but the net result is my python code is not found. e.g 

```
[[embedded_python_run]]
mode = "module"
module = "artipy.__main__"
```

produces an error when run of 
```
ModuleNotFoundError: __path__ attribute not found on 'artipy' while trying to find 'artipy.__main__'
```
I don't think that there is a problem in your code per-se, perhaps more of a documentation issue.  I think that your startup example should package a hello_world.py rather than running a 'repl'. It would help those of us trying to adopt pyoptimizer.

**Comment by indygreg** [comment]
There might be an issue in the code: setting up all the special attributes like `__path__` on modules can be tricky and I wouldn't be surprised if PyOxidizer doesn't conform to required behavior!

In this case, PyOxidizer's memory importer doesn't set `__path__`, hence the error you are seeing.

The behavior of `__path__` is documented at https://docs.python.org/3/reference/import.html#module-path. On my first read of that document, it appears PyOxidizer is in the wrong here because `__path__` *must* be set if a module is a package. Although it can be an empty value (which is likely what PyOxidizer would set it to since there are no _paths_ for in-memory modules).

This feels like a legitimate bug in PyOxidizer. Thank you for reporting it!

**Comment by TxBillbr** [comment]
I'll try to move my project closer to the root directory and see if that sneaks under the path-length limit to get around this for now.

**Comment by Alex-Mann** [comment]
Just wanted to follow up on this... I am pretty sure this is a legitimate bug as I set everything up in the .bzl file and open up a repl just to interactively check the attributes and `<PACKAGE>.__path__` returns an empty array.

Any tips toward where in the source code this stuff gets set up? I'm happy to investigate and submit a PR.

**Comment by indygreg** [comment]
Looking at this today, Python mandates that `__path__` be defined. So the lack of this attribute on in-memory imports is a bug. I may have a fix in for this today...
