### ISSUE TITLE
`CapturedX509Certificate::verify_signed_data` does not always verify correctly

### ISSUE THREAD

**Issue by Hainish** [indygreg/PyOxidizer#528]
When checking against a signed `jar` file, `jarsigner` verifies the signatures of these files:

https://f-droid.org/repo/index-v1.jar
https://apt.izzysoft.de/fdroid/repo/index-v1.jar

This is checked by unzipping the `jar` file and checking the signature block in the `META-INF/*.RSA` file against `META-INF/*.SF`.  It looks like this does not verify correctly when using `CapturedX509Certificate::verify_signed_data`.  The POC has been updated to present this failed verification:

https://github.com/Hainish/parse-ber-poc

```shell
user@rust ~/workspace/parse-ber-poc (master) $ jarsigner -verify signed-jars/f-droid.org.jar 

jar verified.

Warning: 
This jar contains entries whose certificate chain is invalid. Reason: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
This jar contains entries whose signer certificate is self-signed.
The SHA1 digest algorithm is considered a security risk. This algorithm will be disabled in a future update.
The SHA1withRSA signature algorithm is considered a security risk. This algorithm will be disabled in a future update.
This jar contains signatures that do not include a timestamp. Without a timestamp, users may not be able to validate this jar after any of the signer certificates expire (as early as 2037-12-08).
POSIX file permission and/or symlink attributes detected. These attributes are ignored when signing and are not protected by the signature.

Re-run with the -verbose and -certs options for more details.
user@rust ~/workspace/parse-ber-poc (master) $ jarsigner -verify signed-jars/apt.izzysoft.de.jar 

jar verified.

Warning: 
This jar contains entries whose certificate chain is invalid. Reason: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
This jar contains entries whose signer certificate is self-signed.
The SHA1 digest algorithm is considered a security risk. This algorithm will be disabled in a future update.
The SHA1withRSA signature algorithm is considered a security risk. This algorithm will be disabled in a future update.
This jar contains signatures that do not include a timestamp. Without a timestamp, users may not be able to validate this jar after any of the signer certificates expire (as early as 2043-07-27).
POSIX file permission and/or symlink attributes detected. These attributes are ignored when signing and are not protected by the signature.

Re-run with the -verbose and -certs options for more details.
user@rust ~/workspace/parse-ber-poc (master) $ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.72s
     Running `target/debug/parse-ber-poc`
Verifying signed-jars/f-droid.org.jar
true
Verifying signed-jars/apt.izzysoft.de.jar
false
user@rust ~/workspace/parse-ber-poc (master) $
```

**Comment by indygreg** [comment]
Thanks again for the terrific bug report!

The buggy verification is produced from a certificate whose public key is of type `1.2.840.113549.1.1.11` (`PKCS#1 v1.5 SHA-256 with RSA`). Its public key is 4096 bit.

We resolve the verification algorithm at https://github.com/indygreg/PyOxidizer/blob/656d1cc745fcf62102d926be7e807dea3956555e/x509-certificate/src/algorithm.rs#L300. This resolves to `ring::signature::signature::RSA_PKCS1_2048_8192_SHA256`, which I'm pretty sure is the correct verification algorithm for this public key type.

However, if we look at the CMS signature, we see the `SignerInfo::digestAlgorithm` field is `1.3.14.3.2.26`, which corresponds to SHA-1.

So this signature was produced with a key advertised as `PKCS#1 v1.5 SHA-256 with RSA` but using SHA-1 digests. Our crate assumes that the digest algorithm to verify against is purely derived from the subject public key info (SPKI) data structure, which in this case says to use SHA-256. Because the digest type mismatch, signature verification fails.

I'm not an expert on this, but the fact that the signing key is using SHA-1 when it advertises itself as SHA-256 seems a bit fishy to me. In all the certificates I've seen so far, the digest algorithm in produced signatures matches the type as advertised by the SPKI structure. However, crypto signature APIs often allow you to pass in whatever algorithm you want for a given signing key, so mismatches can occur.

We'll likely need to build out some better APIs to allow specifying an alternative digest algorithm to verify with instead of deriving it from the SPKI structure.

**Comment by indygreg** [comment]
It may be worth reading the commit messages and diffs that this issue's timeline references.

Ultimately, there wasn't a problem in the crates in this repo but in the way the reproduce code was performing cryptographic verification. The code was calling into lower-than-CMS level APIs in the x509-certificate crate for performing verification because it needed to verify a signature against external data. The code ignored the metadata on the CMS signature indicating the appropriate digest algorithm to use.

I could point fingers and say the reproduce code was buggy. (It was.) However, that code had to be written the way it was because the CMS signatures in this jar couldn't be validated with existing APIs in the `cryptographic-message-syntax` crate because we didn't offer a way to validate signatures using data not defined as part of the CMS `SignedData` structure. Because of this limitation, you reached for the next best thing/API and inadvertently ignored important metadata about which digest algorithm to use during signature verification.

To me, this represents a deficiency in API design.

The `x509-certificate` and `cryptographic-message-syntax` crates have been taught new APIs to hopefully mitigate this from happening again. Specifically, the latter now has a `SignerInfo::verify_signature_with_signed_data_and_content()` to allow signature verification while providing the exact signed content to verify against. This API will honor the metadata in the CMS signature to use the appropriate digest algorithm. And the `x509-certificate` crate now has an API that allows signature verification using a caller-provided verification algorithm. This will allow verification in scenarios when the signature's digest algorithm doesn't match the digest algorithm as advertised by the public key.

**Comment by Hainish** [comment]
Thanks again for the quick support.  Any idea when you'll be making the release?

**Comment by indygreg** [comment]
x509-certificate v0.10.0 and cryptographic-message-syntax v0.11.0 have been published to crates.io.
