### ISSUE TITLE
Error for setup.py install: `stream did not contain valid UTF-8`

### ISSUE THREAD

**Issue by Schille** [indygreg/PyOxidizer#579]
Hi. Thanks for this awesome tool!

I am currently working on a single executable for Windows. Unfortunately I am facing the following error when compiling `pywin32` with `flavor = standalone_static`:
```bash
[...]
PySID.cpp
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', pyoxidizer\src\py_packaging\packaging_tool.rs:336:38
stack backtrace:
   0:     0x7ff78a963f1f - <unknown>
   1:     0x7ff78a98827a - <unknown>
[...]
```

Since I cannot load the _.dlls_ coming with the `pip install pywin32` I am trying to compile it myself.
```bash
[...]
exe.add_python_resources(exe.setup_py_install("./build/pywin32/"))
[...]
```
with the `setup.py` of `pywin23` being at this location. The compilation runs up to the file `PySID.cpp` (ref: https://github.com/mhammond/pywin32/blob/b304/win32/src/PySID.cpp). At this point I am a bit lost.

Here are the component versions I am using:
Windows 11
PyOxidizer 0.20.0
pywin32 3.9.304.0
Windows 10 SDK version 10.0.19041.0

If you need more information please let me know.

**Comment by indygreg** [comment]
This is due to an `.unwrap()` that shouldn't have existed in the first place. I'll change this to handle invalid UTF-8 output.

Thank you for the bug report!

While I'm here, you may want to avoid `standalone_static` on Windows. It is very brittle. There's a reason it isn't the default. The documentation probably should be more clear about the risks.
