### ISSUE TITLE
OxidizedFinder not found on sys.meta_path[0]

### ISSUE THREAD

**Issue by kwsmith1** [indygreg/PyOxidizer#602]
I'm new to this library and running into a problem. I've created a build but when I try to run a Python script through my embedded interpreter I'm getting this message:

`error instantiating embedded Python interpreter: OxidizedFinder not found on sys.meta_path[0] (this should never happen)`

I've searched around but can't find a straightforward answer anywhere. The 'this should never happen' part is especially discouraging. 

Anyone have an idea how to move past this error?

**Comment by indygreg** [comment]
Do you have steps to reproduce?

I want to say this is reproducible by writing custom Rust code. But looking at the interpreter initialization code in `pyembed`, it is difficult for me to see how this error could occur. Although there is a `TODO` in `remove_external_importers()` that may be the source of this.

**Comment by indygreg** [comment]
This can be caused by a `.pth` file in `site-packages` installing its own meta path importer. And in recent months modern versions of `setuptools` employ such a trick. We'll need to shore up the `sys.meta_path` code to be more tolerant of additional meta path importers.

A short term workaround is to disable the import of the `site` module at interpreter initialization time. e.g. `site_import = False` in Starlark. https://gregoryszorc.com/docs/pyoxidizer/0.22.0/pyoxidizer_config_type_python_interpreter_config.html#starlark_pyoxidizer.PythonInterpreterConfig.site_import
