### ISSUE TITLE
Would supporting dynamic linking to C/C++ extensions make sense?

### ISSUE THREAD

**Issue by madig** [indygreg/PyOxidizer#97]
More an idle thought than an issue: Similarly how Python dependencies that need `__file__` can  be bundled into a `lib/` subdirectory, could C/C++ extensions be bundled and dynamically linked? This would maybe make supporting binary-only wheels like PyQt trivial. I'm however not familiar with the gory details of Rust and dynamic linking, so I might be completely wrong.

**Comment by indygreg** [comment]
Yes, supporting dynamically linked extensions should be doable. It's arguably an easier problem to solve than single file executables. There's still _DLL hell_, especially on Linux. But with binary wheels that don't link against system libraries other than libc and other libraries in the Linux Shared Base, it should be doable.

It's just been low priority for me because I wanted PyOxidizer to bring something to the table that hadn't been done before. A single tool producing self-contained executables without runtime quirks on multiple platforms hadn't been done before :)
